### ISSUE TITLE
Scanning multiple codes at same time

### ISSUE THREAD

**Issue by lasseron** [bitpay/cordova-plugin-qrscanner#114]
Hi, I'm implementing it for a mobile ticket scanner an in my case the camera often sees multiple QR codes at the same time. It seems that the plugin currently scans the code whichever it sees first and there is no way for the user to know which one was scanned. I can think of several solutions:

A. The scanner displays a visual clue (eg green rectangle) around the code which was scanned.
B. The scanner will return a result only when it sees one code. If many codes are visible, it waits for the user to position camera so that only one is fully in view. I know some similar plugins work like this.
C. (Originally "B" by mistake, thx EliArtist!) The scanner will return an array of all visible codes.

I wonder if any of these solutions are available?

**Comment by EliArtist** [comment]
For the second B (i guess it should be C :D ) +1

**Comment by bitjson** [comment]
This is possible by reading the `points` object returned in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) 🚀

**Comment by connyhald** [comment]
@bitjson Where can I find out more about the "points" object? Looked at the README and the last commits but couldn't find anything.

**Comment by bitjson** [comment]
@connyhald it's from here: https://github.com/edi9999/jsqrcode/issues/35 – no further documentation yet, but we probably won't document it here, since we need to migrate away from that package: https://github.com/bitpay/cordova-plugin-qrscanner/issues/169

It's also not currently available in the native platforms.

(Though there will be an upgrade path, since jsQR also provides the same feature.)

**Comment by connyhald** [comment]
@bitjson Thanks for the pointer!
