### ISSUE TITLE
No video preview showing (black screen)  on ios

### ISSUE THREAD

**Issue by netinkumar** [bitpay/cordova-plugin-qrscanner#125]
i am using this plugin in ionic 2. camera preview is there in android but in ios i am getting a black screen and no preview.

**Comment by pedrohymino** [comment]
Try this:

in app.scss
`html,
body.transparent-body,
.transparent-body,
.transparent-body ion-app,
.transparent-body .app-root,
.transparent-body ion-nav,
.transparent-body .ion-page, .transparent-body .nav-decor,
.transparent-body ion-content,
.transparent-body .viewscan,
.transparent-body .fixed-content,
.transparent-body .scroll-content
{
    background-color: transparent !important;
    background: transparent !important;
}`

in page.ts (my case is home.ts)
`scanQRCode(showcam:boolean) {
    this.qrScanner.prepare().then((status: QRScannerStatus) => {
      if (status.authorized) {
        window.document.querySelector('body').classList.add('transparent-body');
        ...
      }
    }
}`

# IMPORTANT!!!
When you change page to open camera (QRScanner), everytime you need use example:
`this.nav.setRoot(HomePage, {}, {animate: false});`
EVERYTIME use animate:false, because animate transition page bug camera in **iOS**, in Android work with animate true or false.

try and comment :)

**Comment by Shuliyey** [comment]
Try remove the `QRScanner.prepare(function(err, status) {...})`

Also make sure to start scanning after the device is ready
```
document.addEventListener('deviceready', function() {...});
```

**Comment by bitjson** [comment]
With the release of, [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17) a lot of these issues are likely to be solved. If you're still having trouble, feel free to open a new issue.

**Comment by zaikin-andrew** [comment]
Thanks, @pedrohymino for https://github.com/bitpay/cordova-plugin-qrscanner/issues/125#issuecomment-336518056 it helped me.

I faced with this issue with 2.6.0 version with Ionic @bitjson 
> "@ionic-native/qr-scanner": "4.10.0"
