### ISSUE TITLE
[Deprecation] Unknown constraint named facingMode rejected

### ISSUE THREAD

**Issue by ricardocamposilva** [bitpay/cordova-plugin-qrscanner#127]
I'm trying to scan but getting the Warning above, when I try to fire the event I get this deprecation message, but no success to open camera view.
There's another message but I don't know if it's also causing this issue.

URL.createObjectURL(stream) is deprecated! Use elem.srcObject = stream instead!

I'm using ionic 3.16.0
Chrome 62.0.3202.75 (Linux)

![issue1](https://user-images.githubusercontent.com/4968970/32511528-27fa555a-c3db-11e7-9aca-936f383f80bc.png)

**Comment by ba-caf** [comment]
I'm getting the same cosole log message(`URL.createObjectURL(stream) is deprecated! Use elem.srcObject = stream instead!`) The difference is that everything functions well.

**Comment by bitjson** [comment]
I think the root issue may be fixed in [2.6.0](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/CHANGELOG.md#260-2018-05-17). The deprecation warnings your seeing shouldn't be a problem (I actually added support for `facingMode` even though no browsers support it yet – a little strange they call it a "deprecation" though).

Closing for now, feel free to open a new issue if you're still having trouble.
