### ISSUE TITLE
Building the tests

### ISSUE THREAD

**Issue by sudham** [bitpay/cordova-plugin-qrscanner#23]
I have a couple of issues -
1. The plugins are not being downloaded from the registry and I am using the git path - not sure how to resolve this
2. The AndroidManifest.xml has a package attribute with a value that contains {{TIMESTAMP}} - this is not being parsed - get an error at "{".  Can I create the package name without this - where should I change this ?

**Comment by bitjson** [comment]
Hey @sudham – could you provide a little more information about your environment? (Are you on Windows? What version of node are you using?)

Are you running `npm run gen-tests`?

For (1), The `gen-tests` task should not be downloading the `cordova-plugin-qrscanner` or `cordova-plugin-qrscanner-tests`, since those are actually [installed from your current working directory](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/tests/project/config.xml#L32) (to allow you to test changes you make).

For (2), the timestamp allows you to test permissions properly by changing the bundle ID each time you `gen-tests` – the `{{TIMESTAMP}}` placeholder should be replaced by the [`timestamp.js`](https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/tests/project/scripts/timestamp.js) script when the tests are generated.

Could you paste the exact output of any errors you're seeing? There might be something that isn't working on your specific environment, and I'd love to make running the tests easy on all platforms.

**Comment by bitjson** [comment]
Hey @sudham – were you able to get the tests built? Please let me know if I should keep this issue open.
