### ISSUE TITLE
Migrate Support Library to AndroidX

### ISSUE THREAD

**Issue by wzijden** [bitpay/cordova-plugin-qrscanner#313]
Hi, for our project, we're forced to use cordova-android@9 (nightly build), which makes this plugin fail on the Android dependency on the support library (CompatActivity).

Can we migrate to AndroidX?

https://developer.android.com/topic/libraries/support-library

https://developer.android.com/jetpack/androidx/migrate

**Comment by rolinger** [comment]
@wzijden - what specifically is failing?

I am running Cordova@9.0.0 with cordova-android@8.1.0 and all is compiling without issue.  I am evening running an old Ionic v1 app too.

You might need to add the `cordova-plugin-androidx` and the `cordova-plugin-androidx-adapter` plugins to your project.  I have both and all is running fine.

**Comment by wzijden** [comment]
@rolinger sorry I meant cordova-android@9 instead of cordova@9 (I updated it). I'm getting a class not found on this line: https://github.com/bitpay/cordova-plugin-qrscanner/blob/master/src/android/QRScanner.java#L27

**Comment by wzijden** [comment]
But it seems adding `cordova-plugin-androidx-adapter` may solve my problem. I'll give that a try.

**Comment by rolinger** [comment]
@wzijden - according to both npm and github, the docs say that the supported version right now for cordova-android is still 8.1.0.  If your forced to be using the dev v9.0 you are def ahead of the curve and are probably going to experience a lot of compatibility issues because so many plugins haven't built support for v9.0 yet.  Hopefully the `androidx-adapter` works for you.

**Comment by wzijden** [comment]
@rolinger Thanks, for the heads up. Yes, I'm just hoping the release will come some time soon. After adding `androidx-adapter` plugin everything seems to be working fine, thanks.
