### ISSUE TITLE
Error when building with Xcode 8 “Use Legacy Swift Language Version” (SWIFT_VERSION)

### ISSUE THREAD

**Issue by agpappas** [bitpay/cordova-plugin-qrscanner#41]
When building with Xcode 8 and Cordova 6.3.1 I get “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Am I missing something?

**Comment by bitjson** [comment]
Try running `cordova prepare ios` again – the plugin will automatically modify your project build settings properly after the prepare step.

I think there may be a bug in cordova preventing this from happening automatically in some cases, though I haven't gotten to pick through it to see.

I'll leave this issue open until I'm able to track down exactly where the problem is.

**Comment by dcousens** [comment]
@agpappas did this resolve your issue?

**Comment by agrath** [comment]
@dcousens 

I'm getting this error message when building via build.phonegap.com with this plugin included.
I can attach a full build log if it would help?

> === BUILD TARGET BootTrack OF PROJECT BootTrack WITH CONFIGURATION Release ===
>Check dependencies
>“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

**Comment by agrath** [comment]
Added:
```
  <preference name="swift-version" value="2.3" />
  <preference name="UseLegacySwiftLanguageVersion" value="true" />
```
To config.xml and build still fails, also tried `<preference name="swift-version" value="3.1" />` based on commit notes suggesting swift was changed to 3.1 recently.
```

**Comment by agrath** [comment]
I've also tried the <preference> nodes under `<platform name="ios"></platform>` with both `<preference name="swift-version" value="2.3" />` and `<preference name="swift-version" value="3.1" />`
Just also tried including from 2.4.1 tag via git rather than NPM;
`<plugin spec="https://github.com/bitpay/cordova-plugin-qrscanner.git#2.4.1" source="git" />` and that fails with a completely different error

**Comment by mosh2151984** [comment]
1- ionic platform remove ios
2- rm -rf plugins/
3- in config.xml

4- in package.json
"dependencies":{
.....
"cordova-plugin-geofence": "git+https://github.com/ypelud/cordova-plugin-geofence.git",
...
}
4- ionic platform add ios
5- Goto : ./platforms/ios/cordova
npm install ios-sim
6- finaly run
ionic run ios --livereload --consolelogs
