### ISSUE TITLE
Using with Ionic: making the background transparent in Ionic 1

### ISSUE THREAD

**Issue by LoneyGG** [bitpay/cordova-plugin-qrscanner#62]
So i managed to get the plugin working all fine and reading the QR's really good but my proble comes with the preview, im not able to make all the ionic bullshit to be transparent, i need help.

```
<ion-view hide-nav-bar="true">
    <ion-content class="transparent" has-header="false" overflow-scroll="false">
      <button class="animated bounceInUp button button-assertive" ng-click="scanQR()" >
          Start Scan
      </button>
    </ion-content>
</ion-view>

```
thats the .html binded to the controller where i call QRScanner.show();

The thing is that the ionic ion-view has a inherit class called "pane" that puts a background, i dont know how to remove that class in this specific page and if i do so in the chrome developer window, i can see the camera preview but the sidemenu is on top of that due to all my elemnts extending from the side-menu.

How can i remove the inherit background of the ionic ion-view without screwing all the app?

I will really apreciate any help, sorry for my english.

Regards

**Comment by bitjson** [comment]
Hey @LoneyGG – you'll need to override the CSS in Ionic as necessary. Depending on what parts of Ionic you're using, it should be relatively easy – here's how [Copay](https://github.com/bitpay/copay/) does it: https://github.com/bitpay/copay/blob/master/src/sass/ionic.scss#L11

The simplest solution is to add to your custom CSS (included after Ionic) statements which override backgrounds you don't need with: `background: none transparent;`

Hope that helps! For more help, I would ask in the Ionic Forums.

(Closing this, since it's really about Ionic, not this plugin, but please let me know if I should reopen.)
